# Generated by Django 6.0.2 on 2026-02-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_lesson_attachment_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='attachment',
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons/materials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='area.lesson')),
            ],
        ),
    ]
