# Generated by Django 6.0.2 on 2026-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kiwify_product_id',
            field=models.CharField(blank=True, help_text='Cole aqui o ID do produto da Kiwify', max_length=255, null=True, unique=True),
        ),
    ]
