# Generated by Django 6.0.2 on 2026-03-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_course_kiwify_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('duvidas', 'Dúvidas de Uso e Configuração'), ('bugs', 'Problemas Técnicos e Bugs'), ('financeiro', 'Financeiro e Faturamento'), ('conta', 'Gestão de Conta e Acessos'), ('sugestoes', 'Sugestões de Melhoria')], max_length=100)),
                ('detalhes', models.TextField()),
                ('media_ticket', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
