# Generated by Django 6.0.2 on 2026-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0009_alter_suportticket_options_suportticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
