# Generated by Django 6.0.2 on 2026-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0010_course_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
